version: "3.7"
services:
  postgres:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    restart: always
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379