default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: RailsApi
  username: postgres
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: RailsApi
  pool: 5
  username: postgres
  password: admin
